-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';



-- -----------------------------------------------------
-- Table `Incident_info`
-- -----------------------------------------------------
CREATE TABLE `Incident_info` (
  `incident_key` VARCHAR(50) NOT NULL,
  `occur_date` DATETIME NULL,
  `occur_time` DATETIME NULL,
  `location_desc` VARCHAR(45) NULL,
  `lon_lat` VARCHAR(50) NOT NULL,
  `jurisdiction_code` VARCHAR(45) NULL,
  `statistical_muder_flag` VARCHAR(45) NULL,
  PRIMARY KEY (`incident_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Victim`
-- -----------------------------------------------------
CREATE TABLE `Victim` (
  `incident_key` VARCHAR(50) NULL,
  `vic_age_group` VARCHAR(45) NULL,
  `vic_sex` VARCHAR(45) NULL,
  `vic_race` VARCHAR(45) NULL,
  INDEX `incident_key_idx` (`incident_key` ASC) ,
  CONSTRAINT `incident_key_v`
    FOREIGN KEY (`incident_key`)
    REFERENCES `Incident_info` (`incident_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Perpetrator`
-- -----------------------------------------------------
CREATE TABLE `Perpetrator` (
  `incident_key` VARCHAR(50) NULL,
  `perp_age_group` VARCHAR(45) NULL,
  `perp_sex` VARCHAR(45) NULL,
  `perp_race` VARCHAR(45) NULL,
  INDEX `incident_key_idx` (`incident_key` ASC) ,
  CONSTRAINT `incident_key_p`
    FOREIGN KEY (`incident_key`)
    REFERENCES `Incident_info` (`incident_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boro_precinct`
-- -----------------------------------------------------
CREATE TABLE `Boro_precinct` (
  `boro` VARCHAR(45) NULL,
  `precinct` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LL_location`
-- -----------------------------------------------------
CREATE TABLE `LL_location` (
  `lon_lat` VARCHAR(50) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lon_lat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Coord_location`
-- -----------------------------------------------------
CREATE TABLE `Coord_location` (
  `lon_lat` VARCHAR(50) NOT NULL,
  `x_coord_cd` VARCHAR(45) NULL,
  `y_coord_cd` VARCHAR(45) NULL,
  PRIMARY KEY (`lon_lat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Key_precinct`
-- -----------------------------------------------------
CREATE TABLE `Key_precinct` (
  `incident_key` VARCHAR(50) NULL,
  `precinct` INT NULL,
  INDEX `incident_key_idx` (`incident_key` ASC) ,
  CONSTRAINT `incident_key`
    FOREIGN KEY (`incident_key`)
    REFERENCES `Incident_info` (`incident_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
