-- MySQL Script generated by MySQL Workbench
-- Thu Nov  5 00:15:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `Scooter`
-- -----------------------------------------------------
CREATE TABLE `Scooter` (
  `scooter_id` INT NOT NULL,
  `manufacturer` VARCHAR(45) NULL,
  `manufacturer_country` VARCHAR(45) NULL,
  `model_num` VARCHAR(45) NULL,
  `range` VARCHAR(45) NULL,
  `weight` INT NULL,
  `top_speed` INT NULL,
  `condition` VARCHAR(45) NULL ,
  PRIMARY KEY (`scooter_id`),
  UNIQUE INDEX `scooter_id_UNIQUE` (`scooter_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Customer_info`
-- -----------------------------------------------------
CREATE TABLE `Customer_info` (
  `customer_id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_num` VARCHAR(45) NOT NULL,
  `borrow_status` INT NULL DEFAULT 0,
  `referral_name` VARCHAR(45) NULL,
  `flagged_customer` VARCHAR(45) NOT NULL DEFAULT 0,
  `adress` VARCHAR(45) NOT NULL,
  `info_date` DATETIME NULL,
  `current_borrowed_sc_id` INT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `current_borrowed_sc_id_idx` (`current_borrowed_sc_id` ASC) ,
  CONSTRAINT `current_borrowed_sc_id`
    FOREIGN KEY (`current_borrowed_sc_id`)
    REFERENCES `Scooter` (`scooter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scooter_usage_info`
-- -----------------------------------------------------
CREATE TABLE `scooter_usage_info` (
  `scooter_id` INT NOT NULL,
  `borrow_date` DATETIME NOT NULL,
  `usage_in_hours` INT NULL,
  `return_date` DATETIME NULL,
  `damage` VARCHAR(45) NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `customerid_borrow_date` VARCHAR(45) NOT NULL,
  `late_return` VARCHAR(45) NULL DEFAULT 0,
  PRIMARY KEY (`customerid_borrow_date`),
  UNIQUE INDEX `customerid_borrow_date_UNIQUE` (`customerid_borrow_date` ASC) ,
  INDEX `scooter_id_idx` (`scooter_id` ASC) ,
  INDEX `customer_id_idx` (`customer_id` ASC) ,
  CONSTRAINT `scooter_id`
    FOREIGN KEY (`scooter_id`)
    REFERENCES `Scooter` (`scooter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `Customer_info` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Freeform`
-- -----------------------------------------------------
CREATE TABLE `Freeform` (
  `notes` TEXT(100) NULL,
  `broken_beyond_repair` INT NULL DEFAULT 0,
  `customerid_borrow_date` VARCHAR(50) NOT NULL,
  `note_number` INT NOT NULL,
  PRIMARY KEY (`customerid_borrow_date`, `note_number`),
  CONSTRAINT `customerid_borrow_date`
    FOREIGN KEY (`customerid_borrow_date`)
    REFERENCES `scooter_usage_info` (`customerid_borrow_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
